export const quotations = [
  {
    id: "QUO-2026-001",
    category: "Software & Licenses",
    quotationTitle: "Software License Renewal",
    department: "IT Department",
    description: "Sample description ",
    submissionDeadline: "2026-02-10T17:00",
    deliveryPeriod: "Within 7 days of order",
    status: "approved",
    items: [
      { id: "1", itemName: "Microsoft Office 365 License", description: "Annual subscription for 50 users", amount: 1250 },
      { id: "2", itemName: "Adobe Creative Cloud", description: "Team license for design department", amount: 980 },
      { id: "3", itemName: "Antivirus Software", description: "Enterprise edition for 100 endpoints", amount: 620 },
      { id: "4", itemName: "Project Management Tool", description: "Premium plan for 30 users", amount: 750 },
      { id: "5", itemName: "Cloud Storage", description: "2TB business plan", amount: 430 },
    ],
  },
  {
    id: "QUO-2026-002",
    category: "Furniture & Equipment",
    quotationTitle: "Office Furniture and Equipment",
    department: "Administration",
    description: "Sample description ",
    submissionDeadline: "2026-02-12T17:00",
    deliveryPeriod: "Within 15 days of order",
    status: "pending",
    items: [
      { id: "1", itemName: "Executive Office Desk", description: "L-shaped desk with cable management", amount: 2100 },
      { id: "2", itemName: "Ergonomic Office Chair", description: "Mesh back with lumbar support", amount: 680 },
      { id: "3", itemName: "Filing Cabinet", description: "4-drawer metal cabinet with lock", amount: 540 },
      { id: "4", itemName: "Conference Table", description: "10-seater wooden conference table", amount: 3200 },
      { id: "5", itemName: "Whiteboard", description: "Magnetic whiteboard 6x4 feet", amount: 260 },
      { id: "6", itemName: "Office Locker", description: "Personal storage locker", amount: 780 },
      { id: "7", itemName: "Bookshelf", description: "5-tier steel bookshelf", amount: 490 },
      { id: "8", itemName: "Reception Desk", description: "Modern reception counter", amount: 1850 },
      { id: "9", itemName: "Visitor Chair", description: "Cushioned waiting chair", amount: 320 },
      { id: "10", itemName: "Desk Lamp", description: "LED desk lamp with USB charging", amount: 150 },
      { id: "11", itemName: "Wall Clock", description: "Digital wall clock", amount: 180 },
      { id: "12", itemName: "Notice Board", description: "Cork board 4x3 feet", amount: 240 },
    ],
  },
  {
    id: "QUO-2026-003",
    category: "IT Infrastructure",
    quotationTitle: "Cloud Infrastructure Upgrade",
    department: "IT Department",
    description: "Sample description ",
    submissionDeadline: "2026-02-13T17:00",
    deliveryPeriod: "Within 10 days of order",
    status: "approved",
    items: [
      { id: "1", itemName: "Cloud Server Migration", description: "AWS EC2 instance setup and migration", amount: 4500 },
      { id: "2", itemName: "Database Optimization", description: "RDS PostgreSQL configuration", amount: 2800 },
      { id: "3", itemName: "Load Balancer Setup", description: "Application load balancer with auto-scaling", amount: 1900 },
    ],
  },
  {
    id: "QUO-2026-004",
    category: "Training & Development",
    quotationTitle: "Employee Training Program",
    department: "HR Department",
    description: "Sample description ",
    submissionDeadline: "2026-02-14T17:00",
    deliveryPeriod: "Program starts within 20 days",
    status: "pending",
    items: [
      { id: "1", itemName: "Leadership Training", description: "3-day workshop for managers", amount: 2200 },
      { id: "2", itemName: "Technical Skills Workshop", description: "Python programming basics", amount: 1600 },
      { id: "3", itemName: "Communication Skills", description: "Effective communication training", amount: 1200 },
      { id: "4", itemName: "Time Management", description: "Productivity enhancement workshop", amount: 900 },
      { id: "5", itemName: "Team Building", description: "Outdoor team building activities", amount: 2500 },
      { id: "6", itemName: "Conflict Resolution", description: "Workshop on workplace conflicts", amount: 1100 },
      { id: "7", itemName: "Diversity Training", description: "Inclusion and diversity awareness", amount: 950 },
      { id: "8", itemName: "Safety Compliance", description: "Workplace safety training", amount: 800 },
    ],
  },
  {
    id: "QUO-2026-005",
    category: "Security Services",
    quotationTitle: "Security System Maintenance",
    department: "Security",
    description: "Sample description ",
    submissionDeadline: "2026-02-15T17:00",
    deliveryPeriod: "Immediate, within 5 days",
    status: "rejected",
    items: [
      { id: "1", itemName: "CCTV System Servicing", description: "Annual maintenance for 50 cameras", amount: 1800 },
      { id: "2", itemName: "Access Control Update", description: "Biometric system software upgrade", amount: 1400 },
      { id: "3", itemName: "Fire Alarm Testing", description: "Complete system check and testing", amount: 950 },
      { id: "4", itemName: "Security Guard Training", description: "Refresher course for security staff", amount: 1100 },
      { id: "5", itemName: "Emergency Lighting", description: "Battery replacement and testing", amount: 720 },
      { id: "6", itemName: "Perimeter Sensors", description: "Calibration and maintenance", amount: 1300 },
    ],
  },
];
