# Generated by Django 6.0.1 on 2026-03-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
     
        migrations.AddField(
            model_name="quotation",
            name="final_qt_verified_accountant",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="quotation",
            name="qt_req_verified_accountant",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="quotation",
            name="qt_verified_principal",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
