# Generated by Django 6.0.1 on 2026-03-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_name_vendor_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="final_qt_verified_accountant",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="qt_req_verified_accountant",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="qt_verified_principal",
            field=models.BooleanField(default=False),
        ),
    ]
