# Generated by Django 6.0.1 on 2026-01-28 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_item_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='approved',
        ),
        migrations.AddField(
            model_name='quotation',
            name='delivery_period',
            field=models.DurationField(default=datetime.timedelta(days=28)),
        ),
    ]
