# Generated by Django 6.0.1 on 2026-03-22 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_quotation_final_qt_verified_accountant_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razorpay_order_id", models.CharField(max_length=256)),
                ("razorpay_payment_id", models.CharField(blank=True, max_length=256)),
                ("razorpay_signature", models.CharField(blank=True, max_length=256)),
                ("amount", models.IntegerField()),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.quotation"
                    ),
                ),
            ],
        ),
    ]
