# Generated by Django 6.0.1 on 2026-03-22 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_quotation_final_qt_verified_accountant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='final_qt_verified_accountant',
            new_name='accountant_verified',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='qt_req_verified_accountant',
            new_name='final_account_verified',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='qt_verified_principal',
            new_name='principal_verified',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('DELIVERED', 'Delivered'), ('PAID', 'Payment Complete')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='DeliveryVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='main.quotation')),
            ],
        ),
    ]
