# Generated by Django 6.0.1 on 2026-01-28 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_quotation_approved_quotation_delivery_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='amount',
        ),
    ]
