# Generated by Django 6.0.1 on 2026-03-22 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_payment'),
        ('main', '0004_rename_final_qt_verified_accountant_quotation_accountant_verified_and_more'),
    ]

    operations = [
    ]
