# Generated by Django 6.0.1 on 2026-03-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20260322_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='accountant_verified',
            new_name='final_qt_verified_accountant',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='final_account_verified',
            new_name='qt_req_verified_accountant',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='principal_verified',
            new_name='qt_verified_principal',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=10),
        ),
    ]
