# Generated by Django 6.0.1 on 2026-01-28 04:10

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_quotation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='category',
            field=models.CharField(default='Administrative', max_length=128),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='submission_deadline',
            field=models.DateTimeField(default=main.models.submission_deadline_default),
        ),
    ]
