# Generated by Django 6.0.1 on 2026-02-02 08:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_quotation_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_model', models.CharField(max_length=256)),
                ('delivery_period', models.DurationField(default=datetime.timedelta(days=28))),
                ('unit_price', models.IntegerField()),
                ('description', models.CharField(max_length=512)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_responses', to='main.item')),
            ],
        ),
    ]
