# Generated by Django 6.0.1 on 2026-03-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0006_rename_accountant_verified_quotation_final_qt_verified_accountant_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="otp_verified",
            field=models.BooleanField(default=False),
        ),
    ]
