# Generated by Django 6.0.1 on 2026-03-25 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_quotation_otp_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotationresponse",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="otp_verified",
        ),
        migrations.AddField(
            model_name="quotation",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotations",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Vendor",
        ),
    ]
