# Generated by Django 6.0.1 on 2026-02-02 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_responseitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationresponse',
            name='amount',
        ),
        migrations.AddField(
            model_name='responseitem',
            name='quotation_response',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='response_items', to='main.quotationresponse'),
        ),
        migrations.AlterField(
            model_name='responseitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_reponses', to='main.item'),
        ),
    ]
