# Generated by Django 6.0.1 on 2026-05-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_quotation_qt_req_verified_principal_paymentarchive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("DELIVERED", "Delivered"),
                    ("SUCCESS", "Success"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
